### ISSUE TITLE
Hola Jere

### ISSUE THREAD

**Issue by lavak00731** [jeremenichelli/jeremenichelli.github.io#6]
Perdón que te moleste pero parece que tu sitio está caido. Abrazo, Ezequiel

**Comment by jeremenichelli** [comment]
Debe haber sido alg'un problema local de red donde estabas vos o un glitch fugaz del server de GitHub Pages. Nunca dejó de funcionar acá.

**Comment by lavak00731** [comment]
Perdona entonces, abrazo
